apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
spec:
  provider: azure
  # Optionally we could load KeyVault secrets as Kubernetes secrets, in addition to mounting them directly into the pods.
  # We don't do it, because currently they're used in another way (from pod filesystem).
  # https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/sync-with-k8s-secrets/
  # secretObjects:
  #   {{- range .Values.kvSecrets }}
  #     - secretName: {{ . | lower | quote }}
  #       type: Opaque
  #       data:
  #       - objectName: {{ . | lower | replace "-" "_" | quote }} # reference to the objectAlias below
  #         key: {{ . | lower | quote }}
  #   {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure.managedIdentityClientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.kvSecrets }}
        - |
          objectName: {{ . | quote }}
          objectAlias: {{ . | lower | replace "-" "_" | quote }}
          objectType: secret
        {{- end }}
