apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: random-max-percent
  value: '50'
  selector:
    namespaces:
      - workload
  duration: '30s'
  scheduler:
    cron: '@every 1m'