apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
  namespace: chaos-testing
spec:
  mode: random-max-percent
  value: '50'
  selector:
    namespaces:
      - workload
  stressors:
    cpu:
      workers: 1
      load: 100
  duration: '60s'
  scheduler:
    cron: '@every 5m'