container:
  containerimage: "OVERWRITE.acr.io/alwayson/CatalogService:1234" # Container Image Name
  pullPolicy: "IfNotPresent" # Container Image Pull Policy. Using IfNotPresent to enable pod starts even if ACR cannot be reached and image was pulled on the node previously

workload:
  domainname: "OVERWRITE-cluster.eastus2.cloudapp.azure.com" # External Domain Name of the AKS cluster (used for Ingress)
  port: 8080 # Port of the container workload
  service:
    port: 80 # Service Port (not used for Ingress)
    type: "ClusterIP" # Service Type (default ClusterIP)

scale:
  minReplicas: 3 # Min Replicas
  maxReplicas: 20 # Max Replicas

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx

azure:
  frontdoorid: "" # Azure Front Door Header ID (blank = disabled)
  region: "East US 2"
  baseurl: "OVERWRITE.myalwaysonapp.net" # FQDN used by the Azure Front Door endpoint

healthservice:
  name: "healthservice-service" # name of the healthservice service in k8s
  port: 80
