apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  ports:
  - port: {{ .Values.workload.service.port | default 80 }}
    protocol: TCP
    targetPort: {{ .Values.workload.port | default 8080 }}
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.workload.service.type | default "ClusterIP" }} 