# Central configuration settings
# used for E2E environment pipelines
variables:

# Resource prefix for this environment
- name:  'prefix'
  value: 'afint'          # <===== CHANGE THIS! Must not be longer than 6 characters! Needs to be a unique prefix

- name: 'stampLocations'
  value: '["northeurope", "brazilsouth"]' # Check which regions are valid. There is a list in /src/infra/README.md

# Terraform state variables
- name:  'terraformResourceGroup'
  value: 'terraformstate-rg'        # <===== CHANGE THIS VALUE IF NEEDED
- name:  'terraformStorageAccount'
  value: '$(prefix)terraformstate'  # Needs to be a globally unique name

# Custom DNS name settings
- name: 'envDnsZoneRG'
  value: 'ao-dns-rg'                # <===== CHANGE THIS OR LEAVE THE VALUE BLANK
- name: 'envDomainName'
  value: 'int.shop.always-on.app'   # <===== CHANGE THIS OR LEAVE THE VALUE BLANK

# Other settings
- name:  'contactEmail'
  value: 'noreply@example.com'  # <===== CHANGE THIS VALUE TO ONE OF YOUR REAL EMAIL ADDRESSES (OR A GROUP)!